package interfaces.mensagens;

/**
 * 
 * @author whesl
 *
 */

public interface IMensagemGeral {
	
	public String ABERTO = "ABERTO";
	public String ACESSO_LIBERADO = "ACESSO LIBERADO!!";
	public String ACESSO_NEGADO = "ACESSO NEGADO!!";
	public String CLIENTE_ALTERADO_SUCESSO = "O CLIENTE FOI ALTERADO COM SUCESSO!!";
	public String CLIENTE_DELETADO_SUCESSO = "O CLIENTE FOI DELETADO COM SUCESSO!!";
	public String CLIENTE_INSERIDO_SUCESSO = "O CLIENTE FOI INSERIDO COM SUCESSO!!";
	public String ESTOQUE_ALTERADO_SUCESSO = "O ESTOQUE FOI ALTERADO COM SUCESSO!!";
	public String ESTOQUE_DELETADO_SUCESSO = "O ESTOQUE FOI DELETADO COM SUCESSO!!";
	public String ESTOQUE_INSERIDO_SUCESSO = "O ESTOQUE FOI INSERIDO COM SUCESSO!!";
	public String FECHADA = "FECHADA";
	public String FUNCIONARIO_ALTERADO_SUCESSO = "O FUNCIONÁRIO FOI ALTERADO COM SUCESSO!!";
	public String FUNCIONARIO_DELETADO_SUCESSO = "O FUNCIONÁRIO FOI DELETADO COM SUCESSO!!";
	public String FUNCIONARIO_INSERIDO_SUCESSO = "O FUNCIONÁRIO FOI INSERIDO COM SUCESSO!!";
	public String LISTAS_INICIALIZADAS = "AS LISTAS PADRÕES FORAM INICIALIDAS COM SUCESSO NO LOCAL STORAGE";
	public String LISTAS_NAO_INICIALIZADAS = "AS LISTAS PADRÕES NÃO FORAM INICIALIDAS, VERIFICAR IMPLEMENTAÇÃO!!!";
	public String MESA_ALTERADA_SUCESSO = "A MESA FOI ALTERADA COM SUCESSO!!";
	public String MESA_DELETADA_SUCESSO = "A MESA FOI DELETADA COM SUCESSO!!";
	public String MESA_FECHADA_SUCESSO = "A MESA FOI FECHADA COM SUCESSO!!";
	public String MESA_NAO_STATUS_ABERTA = "A MESA NÃO ESTÁ COM O STATUS ABERTA!!";
	public String MESA_INSERIDA_SUCESSO = "A MESA FOI INSERIDA COM SUCESSO!!";
	public String USUARIO_ALTERADO_SUCESSO = "O USUÁRIO FOI ALTERADO COM SUCESSO!!";
	public String USUARIO_DELETADO_SUCESSO = "O USUÁRIO FOI DELETADO COM SUCESSO!!";
	public String USUARIO_INSERIDO_SUCESSO = "O USUÁRIO FOI INSERIDO COM SUCESSO!!";
	public String PRODUTO_ALTERADO_SUCESSO = "O PRODUTO FOI ALTERADO COM SUCESSO!!";
	public String PRODUTO_DELETADO_SUCESSO = "O PRODUTO FOI DELETADO COM SUCESSO!!";
	public String PRODUTO_INSERIDO_SUCESSO = "O PRODUTO FOI INSERIDO COM SUCESSO!!";
	
	public Integer LIMITE_MESAS_ESTABELECIMENTO = 10;
	
}
